version: "3"

services:
  database:
    image: mariadb:latest

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    networks:
      database_net:

    volumes:
      - database_data:/var/lib/mysql

  backend:
    build:
      dockerfile: ./Backend.dockerfile

    environment:
      DB_URL: ${DB_URL}
      LISTEN_ADDR: 0.0.0.0:3000
      RUST_LOG: info

    ports:
      - 3000:3000

    networks:
      database_net:
      backend_net:
      prometheus_net:

  dashboard:
    build:
      dockerfile: ./Dashboard.dockerfile

    ports:
      - 8088:80

    networks:
      backend_net:

  cloudbeaver:
    image: dbeaver/cloudbeaver

    networks:
      database_net:

    ports:
      - 8080:8978

    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

  prometheus:
    image: prom/prometheus:latest

    volumes:
      - ./prometheus:/etc/prometheus:ro

    ports:
      - 9092:9090

    networks:
      prometheus_net:

networks:
  backend_net:
  database_net:
  prometheus_net:

volumes:
  database_data:
  cloudbeaver_data:
