{
 "title": "Serverless WASM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUSBACKEND", "query": "PrometheusBackend" }
  ]
 },
 "panels": [
  {
   "title": "New Users (since restart)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Function Calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "function_call_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Function Call Response Times",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(function_call_response_time_bucket[1d])) by (le))\n",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}