---
apiVersion: 1

datasources:
  - name: PrometheusBackend
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.37.0
      cacheLevel: High
