---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service-collector'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'master-node-exporter'
    static_configs:
      - targets: ['master_exporter:9100']
