//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::function::Entity as Function;
pub use super::module::Entity as Module;
pub use super::user::Entity as User;
pub use super::wallet::Entity as Wallet;
